Engine/include/creature.h, Engine/include/environment.h, Engine/include/simulationdata.h, Engine/src/creature.cpp, Engine/src/food.cpp, Engine/src/movable_entity.cpp, Engine/src/simulationdata.cpp
Add creature energy functionalities such as die, updateEnergy
=> Creature energy

Engine/include/entity.h, Engine/include/environment.h, Engine/include/movable_entity.h, Engine/src/entity.cpp, Engine/src/movable_entity.cpp, Engine/src/simulationdata.cpp
Coordinates of movable entities now always stay within map bounds. Changed SetCoordinates function in Entity class, Move function in Movable Entity class and MoveAllCreatures in SimulationData
=> Implement torus map

Engine/include/creature.h, Engine/include/entity.h, Engine/include/food.h, Engine/include/movable_entity.h
=> Change properties of entity and subclasses to Protected

Engine/include/entity.h, Engine/src/simulationdata.cpp, Engine/tests/CMakeLists.txt, Engine/tests/collisions.cpp, Engine/tests/neat.cpp
- added gtests for collisions 
- will add more once we will have just one grid 
- spotted a mistake in the circle-line collisions that Berra will fix soon (but nothing urgent as we don't use these types of collisions yet)
=> System links/gtest-collisions-ESH-62

Engine/include/creature.h, Engine/src/creature.cpp
Added a member function `GetClosestFood` to `Creature` class. The function takes as arguments:
-grid (`std::unordered_map<int, std::unordered_map<int, std::vector<Entity*> > > &grid`) whose cells contain a vector of pointers to entities, every cell must contain such vector, possibly empty 
-size of a grid cell ( `double GridCellSize`).
It return a pointer to the closest food object (closest to the current creature).
=> Implemented closest food

Engine/include/environment.h, Engine/src/simulation.cpp, Engine/src/simulationdata.cpp, Engine/tests/collisions.cpp, UI/src/simulationcanvas.cpp
- checked neighbouring cells for collisions
- displayed size of entities in the UI
- fIxed bug in collision gtests
=> Display size, check neigbouring cells

UI/include/mainwindow.h, UI/include/simulationcanvas.h, UI/src/mainwindow.cpp, UI/src/mainwindow.ui, UI/src/simulationcanvas.cpp
Basic graph display functions, one of them doesn't work yet, will fix it tmrw.
=> My work for the week

Engine/include/creature.h, Engine/include/entity.h, Engine/src/creature.cpp
Add method for creature growth and attribute for growth to energy consumption ration.
=> Add creature growth

Engine/include/creature.h, Engine/include/entity.h, Engine/include/simulationdata.h, Engine/src/creature.cpp, Engine/src/entity.cpp, Engine/src/simulationdata.cpp
Grid changed from unordered map of ints to matrix of vectors with pointers to entities. Fixed a lot of bugs with the implementation of it and of collisions (sorry).
=> Vector Grid and Fixed Bugs

UI/src/qsfmlcanvas.cpp
- Fixed QSFMLCanvas compile error for Linux platforms
=> Fix QSFMLCanvas for Linux

Engine/include/config.h, Engine/include/creature.h, Engine/include/entity.h, Engine/include/movable_entity.h, Engine/src/creature.cpp, Engine/src/entity.cpp, Engine/src/simulation.cpp, Engine/src/simulationdata.cpp
Primitive brain movement implemented
=> System links/brain movement

Engine/include/creature.h, Engine/include/entity.h, Engine/include/movable_entity.h, Engine/src/creature.cpp, Engine/src/entity.cpp, Engine/src/movable_entity.cpp, Engine/src/simulationdata.cpp, Engine/tests/collisions.cpp
- OnCollision is now takes (other_entity, kMapWidth, kMapHeight) as parameter
=> Collision for entity

Engine/src/engine.cpp, Engine/src/entity.cpp, Engine/src/simulationdata.cpp
When changing food density from the UI, the collision grid wasn't getting updated
=> Fixed segmentation fault when checking collisions

Engine/include/engine.h, Engine/include/environment.h, Engine/include/simulation.h, Engine/include/simulationdata.h, Engine/src/engine.cpp, Engine/src/entity.cpp, Engine/src/environment.cpp, Engine/src/food.cpp, Engine/src/simulation.cpp, Engine/src/simulationdata.cpp, Engine/tests/collisions.cpp
Added gtests for the initializing grid and for correct placement in grid. Changed environment to be in a namespace so that I can test.
=> Add grid tests

Engine/include/creature.h, Engine/include/entity.h, Engine/src/creature.cpp, Engine/src/entity.cpp, Engine/tests/collisions.cpp
Changed GetDistance function entity to calculate the distance according to the torus map.
=> torus map fix

Engine/include/food.h, Engine/src/food.cpp
=> Food and Meat fixed

Engine/include/creature.h, Engine/src/collisions.cpp, Engine/src/creature.cpp, Engine/tests/CMakeLists.txt, Engine/tests/collisions.cpp, Engine/tests/creature.cpp
Add implementation of health with different dynamics to manage it. Also add age of creatures which limits max_energy_
=> Fix energy health

Engine/include/config.h, Engine/src/engine.cpp
Eliminate the food intialization call after doing a change in food density from the ui
=> Food density change doesn't initialize food

Engine/include/entity.h, Engine/src/entity.cpp
=> Add entity id

Engine/src/mutable.cpp
=> Documentation

Engine/include/config.h, Engine/include/neat/neat-genome.h, Engine/include/neat/neat-neural-network.h, Engine/include/neat/neat-neuron.h, Engine/src/movable_entity.cpp, Engine/src/neat/neat-genome.cpp, Engine/src/neat/neat-neural-network.cpp, Engine/src/neat/neat-neuron.cpp
Implemented random mutation of activation function.
Main difficulty was maintaining structural alignment between ffneurons and neurons, please check if its right. I use a pointer to the genome of the current neural network instance to find the corresponding neuron of the current ffneuron during traversal: to get the correct activation function to use.
No rush to check, and happy holidays :)
=> Activation mutation

Engine/include/food.h, Engine/src/food.cpp, Engine/src/simulationdata.cpp, UI/src/simulationcanvas.cpp
Specified a version of the template function UpdateGrid to add meat to the food vector if a creature dies.
=> creatures become meat

Engine/include/config.h, Engine/include/neat/neat-genome.h, Engine/include/neat/neat-link.h, Engine/include/neat/neat-neural-network.h, Engine/include/neat/neat-neuron.h, Engine/src/movable_entity.cpp, Engine/src/neat/neat-genome.cpp, Engine/src/neat/neat-link.cpp, Engine/src/neat/neat-neural-network.cpp, Engine/src/neat/neat-neuron.cpp, Engine/tests/collisions.cpp, Engine/tests/neat.cpp
Reverts EvolutionSimulator/EvolutionSimulator#118
=> Revert "Neat speciation/main"

Engine/include/simulationdata.h, Engine/src/creature.cpp, Engine/src/simulationdata.cpp
Optimized the reproduction function so that it doesn't repeat checks from iteration to iteration which created a lot of lag after a while of running the simulation
=> Reproduction optimization

Engine/include/simulationdata.h, Engine/src/simulationdata.cpp
Fix in reproduction that created an infinite loop
=> Reproduction fix

Engine/CMakeLists.txt, Engine/include/config.h, Engine/include/creature.h, Engine/include/egg.h, Engine/include/food.h, Engine/src/creature.cpp, Engine/src/egg.cpp
Enables the eggs to be edible if they are added to food_entities_ vector when reproduction system is implemented.
=> Restructuring of Egg Class (Inheritence)

Engine/CMakeLists.txt, Engine/include/config.h, Engine/include/creature.h, Engine/include/environment.h, Engine/include/settings.h, Engine/include/simulationdata.h, Engine/src/creature.cpp, Engine/src/engine.cpp, Engine/src/environment.cpp, Engine/src/simulation.cpp, Engine/src/simulationdata.cpp, UI/Shaders/densityShader.frag, UI/include/mainwindow.h, UI/include/simulationcanvas.h, UI/qrc_resource_file.qrc, UI/src/main.cpp, UI/src/mainwindow.cpp, UI/src/mainwindow.ui, UI/src/simulationcanvas.cpp, settings.json
Add food density as a map setting, wrapping infinite and like a couple other things
=> Map settings/rebased

Engine/CMakeLists.txt, Engine/include/config.h, Engine/include/neat/brain_module.h, Engine/include/neat/neat-genome.h, Engine/src/creature.cpp, Engine/src/neat/brain_module.cpp, Engine/src/neat/neat-genome.cpp, Engine/tests/neat.cpp
=> Modular brain/modules

UI/include/mainwindow/config_manager.h, UI/include/mainwindow/graph_manager.h, UI/src/mainwindow/config_manager.cpp, UI/src/mainwindow/graph_manager.cpp, UI/src/mainwindow/mainwindow.cpp
After restart, i was not setting up the graph manager and config manager to have the pointer to the new engine. Seems to work now
=> Fix restart/main

UI/include/mainwindow/graph_manager.h, UI/include/simulationcanvas/simulationcanvas.h, UI/src/mainwindow/graph_manager.cpp, UI/src/mainwindow/mainwindow.cpp, UI/src/simulationcanvas/simulationcanvas.cpp
=> Selection scatter

Engine/include/settings.h, Engine/src/creature.cpp
=> Quick age hot fix

Engine/include/food.h, Engine/include/grabbing_entity.h, Engine/include/movable_entity.h, Engine/include/mutable.h, Engine/include/neat/brain_module.h, Engine/include/neat/neat-genome.h, Engine/include/settings.h, Engine/include/vision_system.h, Engine/src/alive_entity.cpp, Engine/src/creature.cpp, Engine/src/creature_manager.cpp, Engine/src/digestive_system.cpp, Engine/src/egg.cpp, Engine/src/entity.cpp, Engine/src/entity_grid.cpp, Engine/src/food.cpp, Engine/src/movable_entity.cpp, Engine/src/mutable.cpp, Engine/src/neat/brain_module.cpp, Engine/src/neat/neat-genome.cpp, Engine/src/neat/neat-neuron.cpp, Engine/src/pheromone.cpp, Engine/src/pheromones_system.cpp, Engine/src/reproduction.cpp, Engine/src/simulation.cpp, Engine/src/vision_system.cpp, Engine/tests/collisions.cpp, Engine/tests/creature.cpp, UI/src/simulationcanvas/simulationcanvas.cpp
This should fix everything that was creating a problem except the start crash
=> Fix crashes

UI/src/simulationcanvas/simulationcanvas.cpp
Mouse coordinates are now warped, stays on while zooming
=> Fix mouse coords
